### ISSUE TITLE
Wrong path in tables.resolver.php

### ISSUE THREAD

**Issue by PsychoBitchy** [Bruno17/migxmultilang#12]
In /_build/resolvers/tables.resolver.php
There's a wrong file path hardcoded:
`$migxmodelPath = $modx->getOption('migx.core_path', null, $modx->getOption('core_path') . 'components/migx/') . 'model/';
                include_once ($migxmodelPath . 'migx/migxpackagemanager.class.php');`
Whereas "migx" should be "migxmultilang" thus causing the MODX plugin installer to fail.
`PHP warning: include_once(/var/www/modx-2.5.1-pl/core/components/migx/model/migx/migxpackagemanager.class.php): failed to open stream: No such file or directory
PHP warning: include_once(): Failed opening '/var/www/modx-2.5.1-pl/core/components/migx/model/migx/migxpackagemanager.class.php' for inclusion (include_path='.:')`

Additionally, migxpackagemanager.class.php doesn't exist **at all** inside the package

**Comment by Bruno17** [comment]
the path is the correct one.
you need to have MIGX installed.

**Comment by PsychoBitchy** [comment]
#Facepalm
It's well written on doc, sorry.
