### ISSUE TITLE
Manager JS Error when editing TV

### ISSUE THREAD

**Issue by marcoglur** [Bruno17/migxmultilang#8]
Not sure if this is a more general issue of MIGX migxdb, but every time I enter a translation, I can't directly edit another translation w/o loading the page again.
I followed this guide: https://rtfm.modx.com/revolution/2.x/case-studies-and-tutorials/create-a-multilingual-website-with-migxmultilang (also checked https://github.com/Bruno17/migxmultilang but no additional hints found)
and the extra friendly URLs is active.

**Browser**
- Safari Version 9.0.3 (11601.4.4)
- Firefox ESR 38.5.2

**MODX**
- MODX Revolution 2.4.2-pl
- MIGX 2.9.6-pl
- pdoTools 2.2.4-pl
- migxMultiLang 1.0.8-pl

Detailed Information:
- clicking _Edit_ first time after closing

```
setLeftTopext-all.js:5415 TypeError: undefined is not an object (evaluating 'b.dom.style')
setLeftTopext-all.js:5415
setLeftTopext-all.js:8576
beforeShowext-all.js:20014
showext-all.js:20044
loadWindowindex.php:52
loadWinmanager:489
updatemanager:427
(anonymous function)ext-base.js:20:8908
onClickmanager:600
Iext-all.js:3524
toFrontext-all.js:20331
```
- clicking _Edit_ second time shows a different error:

```
toFrontext-all.js:21:380725 TypeError: undefined is not an object (evaluating 'this.manager.bringToFront')
toFrontext-all.js:20331
showext-all.js:20029
loadWindowindex.php:52
loadWinmanager:489
updatemanager:427
(anonymous function)ext-base.js:20:8908
onClickmanager:600
Iext-all.js:3524
```

As a workaround, first all content for a language has to be filled, then save and load the backend again for editing the next translation contents. It would be great to figure this problem out for having a more convenient UX on translating to multiple languages at once.

**Comment by Bruno17** [comment]
try this:
https://github.com/Bruno17/migxmultilang/commit/56cc149dfcab046700bad243db9913d163543a76

**Comment by marcoglur** [comment]
That was a very good help. Thanks for saving my day, worked like a charm!
